version: '2.0'

services:

  test:
    image: delxys/test
    restart: always
    ports:
      - 3000:3000

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - 9000:9000